version: '3'
  
services:
  nginx:
    build: client
    ports: 
        - "80:80"
    volumes:
        - /home/samfeng/open-chromatin-db/client/public/files:/usr/share/nginx/html/files
        - /home/vnelakuditi/JBrowse_test:/var/www/jbrowse
    networks:
        - docker

networks:
  docker:
    ipam:
      driver: default
      config:
        - subnet: 10.10.12.1/22 
