version: '3'

services:
  mysql:
    image: mysql:5.7.22
    volumes: 
      - /home/samfeng/open-chromatin-db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bed
      - MYSQL_USER=node-user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      - open-cd
  node:
    build: server
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - open-cd
  react:
    build: client
    ports:
      - "3000:3000"
    depends_on: 
      - node
    networks:
      - open-cd

networks:
  open-cd:
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.1/22
