version: '3'

services:
  node:
    build: server
    ports:
      - "3001:3001"
    volumes: 
      - /home/samfeng/open-chromatin-db/data:/usr/src/data
    networks:
      - open-cd
  react:
    build: client
    ports:
      - "80:80"
    depends_on: 
      - node
    networks:
      - open-cd
  jbrowse:
    build: jbrowse
    ports:
      - "3002:3002"
    volumes:
      - /home/samfeng/open-chromatin-db/jbrowse/data:/usr/src/app/data
    networks: 
      - open-cd

networks:
  open-cd:
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.1/22
